name: ci-deploy

on: 
  push:
    branches: 
      - master
      
jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-north-1
    - name: AWS Canary Monitoring
      uses: janerikcarlsen/aws-canary-monitoring@master
      with:
        alarm-name: Synthetics-Alarm-my-canary-monitor
        monitoring-time: 2

